### ISSUE TITLE
TinyMCE options that expect JavaScript functions are not supported

### ISSUE THREAD

**Issue by mykwillis** [aljosa/django-tinymce#152]
There are several TinyMCE options (`color_picker_callback`, `file_browser_callback`, `images_upload_handler`, etc.) that expect to receive a JavaScript function as their value. But because django-tinymce serializes all of the configuration options as JSON, functions cannot be passed through from Python.

For example, if I had a JavaScript function `myColorPicker` that I wanted to install as the `color_picker_callback`, I'm out of luck:

``` Python
TINYMCE_DEFAULT_CONFIG = {
  'color_picker_callback': ??? # No way to specify the JavaScript function
}
```

I've submitted a pull request https://github.com/aljosa/django-tinymce/pull/151 that allows you to specify the _name_ of a JavaScript function in the Python configuration code. This name is resolved in the JavaScript initialization code, before calling `tinymce.init`. So, you could do something like:

``` Python
TINYMCE_DEFAULT_CONFIG = {
  'color_picker_callback': 'myColorPicker'  # name of function assumed to be defined in JS
}
```

This seems to work well for my needs.

**Comment by mattarchie** [comment]
I found a similar issue for the paste plugin's paste_preprocess and paste_postprocess options. When setting those in TINYMCE_DEFAULT_CONFIG, you can declare the function inline:
```'paste_postprocess':"function(pl, o) { o.content = strip_tags(o.content,'<div>');}"```

However, as I reported in #166 and fixed in #168, this isn't handled properly when adding the js function to the configuration dictionary. If you could check for any/all parameters that use callback functions in the same place where it checks for these two paste callbacks, then you could directly handle any inline anonymous functions and perhaps pass another list to the js that you could use in your method for resolving the function names.
